filebeat.prospectors:
- type: log
  paths:
   - '/var/lib/docker/containers/*/*.log'
  json.message_key: log
  json.keys_under_root: false
  processors:
  - add_docker_metadata: ~
output.kafka:
  hosts: ["kafka0:9092", "kafka1:10092", "kafka2:11092","kafka3:12092"]
  topic: 'filebeat'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000