version: "3"

services:
  kafka0:
    image: "hyperledger/fabric-kafka:x86_64-0.4.7"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2182,zookeeper2:2183
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=poc-net
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=16000
      - KAFKA.MIN_INSYNC_REPLICAS=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
    networks:
      poc-net:
        aliases:
          - kafka0
  kafka1:
    image: "hyperledger/fabric-kafka:x86_64-0.4.7"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2182,zookeeper2:2183
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=poc-net
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=16000
      - KAFKA.MIN_INSYNC_REPLICAS=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "10092:9092"
    networks:
      poc-net:
        aliases:
          - kafka1
  kafka2:
    image: "hyperledger/fabric-kafka:x86_64-0.4.7"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2182,zookeeper2:2183
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=poc-net
      - KAFKA_BROKER_ID=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=16000
      - KAFKA.MIN_INSYNC_REPLICAS=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "11092:9092"
    networks:
      poc-net:
        aliases:
          - kafka2
  kafka3:
    image: "hyperledger/fabric-kafka:x86_64-0.4.7"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2182,zookeeper2:2183
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=poc-net
      - KAFKA_BROKER_ID=4
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=16000
      - KAFKA.MIN_INSYNC_REPLICAS=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "12092:9092"
    networks:
      poc-net:
        aliases:
          - kafka3

networks:
  poc-net:
    external:
      name: poc-net