version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    volumes:
      - ../data/elastic/elasticsearch/data:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
    networks:
      poc-net:
        aliases:
          - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    volumes:
      - ../configs/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    deploy:
      replicas: 1
    networks:
      poc-net:
        aliases:
          - logstash

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.4.0
    command: filebeat -e -strict.perms=false
    user: root
    ports:
      - '5044:5044'
    volumes:
      - ../configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    networks:
      poc-net:
        aliases:
          - filebeat

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.4.0
    command: metricbeat -e -strict.perms=false
    user: root
    volumes:
      - ../configs/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    networks:
      poc-net:
        aliases:
          - metricbeat

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
    deploy:
      replicas: 1
    networks:
      poc-net:
        aliases:
          - kibana

networks:
  poc-net:
    external:
      name: poc-net